<a href="https://colab.research.google.com/github/oyinig/African-AI-Foundation/blob/main/ConvertFileToNum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 16.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 35.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 41.1 MB/s eta 0:00:00


In [3]:
import ipywidgets as widgets
from IPython.display import display
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from google.colab import files
import shutil
import os
import io
from transformers import Wav2Vec2FeatureExtractor, AutoTokenizer
import torchaudio
from torchaudio.transforms import Resample


Convert an image in the content folder to numbers

In [13]:

def image_to_matrix():
    image = Image.open('/content/sample_data/Images/image.jpeg')
    # Convert the image to grayscale
    image_gray = image.convert('L')
    # Convert the grayscale image to a numpy array
    matrix_grey = np.array(image_gray)
    print("Grey", matrix_grey)
    matrix_coloured = np.array(image)
    print("Coloured", matrix_coloured)
    print("Grey Shape", matrix_grey.shape)
    print("Coloured Shape", matrix_coloured.shape)
    np.savetxt("/content/image_data.csv", matrix_grey)


image_to_matrix()

Grey [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
Coloured [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
Grey Shape (213, 237)
Coloured Shape (213, 237, 3)


In [17]:
def extract_audio_features():
    audio_file = '/content/sample_data/Audio/sample-3s.mp3'

    waveform, original_sample_rate = torchaudio.load(audio_file)

    # Resample the audio waveform to 16000 Hz
    resample_transform = Resample(orig_freq=original_sample_rate, new_freq=16000)
    resampled_waveform = resample_transform(waveform)

    # Initialize Wav2Vec2 feature extractor
    feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained("facebook/wav2vec2-base-960h")

    # Extract audio features
    features = feature_extractor(resampled_waveform, sampling_rate=16000, return_tensors="pt")
    np.save('/content/extracted_audio_features.npy', features.input_values.numpy())
    print(features)
    print(features.input_values.shape)

extract_audio_features()

{'input_values': tensor([[[-0.2358,  0.0660,  0.2489,  ..., -0.2437,  0.0678,  0.2143],
         [-0.2358,  0.0660,  0.2489,  ..., -0.2437,  0.0678,  0.2143]]])}
torch.Size([1, 2, 51131])


In [15]:
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Input words
input_words = "Convert these words to numbers. African AI Foundation is creating an army of AI champions"

# Tokenize the input words
tokens = tokenizer(input_words, return_tensors="pt")

# Convert tokens to numbers (token IDs)
token_ids = tokens['input_ids']

print("Input Words:", input_words)
print("Token IDs:", token_ids)



Input Words: Convert these words to numbers. African AI Foundation is creating an army of AI champions
Token IDs: tensor([[  101, 10463,  2122,  2616,  2000,  3616,  1012,  3060,  9932,  3192,
          2003,  4526,  2019,  2390,  1997,  9932,  3966,   102]])
