<a href="https://colab.research.google.com/github/oyinig/African-AI-Foundation/blob/main/ConvertFileToNum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!pip install transformers

In [10]:
import ipywidgets as widgets
from IPython.display import display
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from google.colab import files
import shutil
import os
import io
from transformers import Wav2Vec2FeatureExtractor, AutoTokenizer
import torchaudio
from torchaudio.transforms import Resample


Convert an image in the content folder to numbers

In [ ]:

def image_to_matrix():
    image = Image.open('/content/sample_data/Images/image.jpeg')
    # Convert the image to grayscale
    image_gray = image.convert('L')
    # Convert the grayscale image to a numpy array
    matrix_grey = np.array(image_gray)
    print("Grey", matrix_grey)
    matrix_coloured = np.array(image)
    print("Coloured", matrix_coloured)
    print("Grey Shape", matrix_grey.shape)
    print("Coloured Shape", matrix_coloured.shape)
    np.savetxt("/content/image_data.csv", matrix_grey)


image_to_matrix()

Grey [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
Coloured [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
Grey Shape (213, 237)
Coloured Shape (213, 237, 3)


In [ ]:
def extract_audio_features():
    audio_file = '/content/sample_data/Audio/sample-3s.mp3'

    waveform, original_sample_rate = torchaudio.load(audio_file)

    # Resample the audio waveform to 16000 Hz
    resample_transform = Resample(orig_freq=original_sample_rate, new_freq=16000)
    resampled_waveform = resample_transform(waveform)

    # Initialize Wav2Vec2 feature extractor
    feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained("facebook/wav2vec2-base-960h")

    # Extract audio features
    features = feature_extractor(resampled_waveform, sampling_rate=16000, return_tensors="pt")
    np.save('/content/extracted_audio_features.npy', features.input_values.numpy())
    print(features)
    print(features.input_values.shape)

extract_audio_features()

{'input_values': tensor([[[-0.2358,  0.0660,  0.2489,  ..., -0.2437,  0.0678,  0.2143],
         [-0.2358,  0.0660,  0.2489,  ..., -0.2437,  0.0678,  0.2143]]])}
torch.Size([1, 2, 51131])


In [50]:
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Input words - Try to make them the same no of words
input_words1 = "Convert these words to numbers. African AI Foundation is creating an army of AI champions"
input_words2 = "Converted the words to numbers. African AI Foundation has created an army of AI champions"
input_words3 =  "The African economy needs to grow for it to become very competitive like the European economy"




# Tokenize the input words
tokens1 = tokenizer(input_words1, return_tensors="pt")
tokens2 = tokenizer(input_words2, return_tensors="pt")
tokens3 = tokenizer(input_words3, return_tensors="pt")

# Convert tokens to numbers (token IDs)
token_ids = tokens['input_ids']


In [51]:
#Cosine Similarity search between token 1 and 2. Higher number means very similar

from numpy import dot
from numpy.linalg import norm

cos_sim = dot(tokens1.input_ids[0], tokens2.input_ids[0])/(norm(tokens1.input_ids[0])*norm(tokens2.input_ids[0]))
cos_sim

0.9622583131501405

In [52]:
#Cosine Similarity search between token 2 and 3. Lower number means less similar

cos_sim = dot(tokens2.input_ids[0], tokens3.input_ids[0])/(norm(tokens2.input_ids[0])*norm(tokens3.input_ids[0]))
cos_sim

0.6601614588771935