<a href="https://colab.research.google.com/github/oyinig/African-AI-Foundation/blob/main/Copy_of_ConvertFileToNum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 25.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 28.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 54.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 56.4 MB/s eta 0:00:00


In [ ]:
import ipywidgets as widgets
from IPython.display import display
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from google.colab import files
import shutil
import os
import io
from transformers import Wav2Vec2FeatureExtractor, AutoTokenizer
import torchaudio
from torchaudio.transforms import Resample


Convert an image in the content folder to numbers

In [ ]:

def image_to_matrix():
    image = Image.open('/content/sample_data/Images/image.jpeg')
    # Convert the image to grayscale
    image_gray = image.convert('L')
    # Convert the grayscale image to a numpy array
    matrix_grey = np.array(image_gray)
    print("Grey", matrix_grey)
    matrix_coloured = np.array(image)
    print("Coloured", matrix_coloured)
    print("Grey Shape", matrix_grey.shape)
    print("Coloured Shape", matrix_coloured.shape)
    np.savetxt("/content/image_data.csv", matrix_grey)


image_to_matrix()

Grey [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
Coloured [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
Grey Shape (213, 237)
Coloured Shape (213, 237, 3)


In [ ]:
, output
import torch
from transformers import ViTFeatureExtractor, ViTForImageClassification
from PIL import Image
import urllib.request

# Load the pre-trained ViT model and feature extractor
model_name = "google/vit-base-patch16-224-in21k"
feature_extractor = ViTFeatureExtractor.from_pretrained(model_name)
model = ViTForImageClassification.from_pretrained(model_name)
output = None
# Load and preprocess the image

image_path = "https://www-konga-com-res.cloudinary.com/w_700,f_auto,fl_lossy,dpr_2.0,q_auto/media/catalog/product/N/B/144458_1647450047.jpg"
urllib.request.urlretrieve(image_path,"image.jpg")
image = Image.open("image.jpg")
inputs = feature_extractor(images=image, return_tensors="pt")


inputs

/usr/local/lib/python3.10/dist-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(
Some weights of ViTForImageClassification were not initialized from the model checkpoint at google/vit-base-patch16-224-in21k and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'pixel_values': tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]])}

In [ ]:
def extract_audio_features():
    audio_file = '/content/sample_data/sample-3s.mp3.wav'

    waveform, original_sample_rate = torchaudio.load(audio_file)

    # Resample the audio waveform to 16000 Hz
    resample_transform = Resample(orig_freq=original_sample_rate, new_freq=16000)
    resampled_waveform = resample_transform(waveform)

    # Initialize Wav2Vec2 feature extractor
    feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained("facebook/wav2vec2-base-960h")

    # Extract audio features
    features = feature_extractor(resampled_waveform, sampling_rate=16000, return_tensors="pt")
    np.save('/content/extracted_audio_features.npy', features.input_values.numpy())
    print(features)
    print(features.input_values.shape)

extract_audio_features()

{'input_values': tensor([[[ 0.0057,  0.0009, -0.0051,  ..., -0.0022, -0.0030, -0.0029]]])}
torch.Size([1, 1, 184960])


## **Converting text to number encoding/embedding**

The numeric encoding carry the semantic meaning of the text

The numbers are not random but based on the word-number matrix/mapping used by the model

If you use a model tokenizer to extract features, you must use the model for other downstream tasks, because each model encodes their embeddings differently





In [ ]:
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Input words - Try to make them the same no of words
input_words1 = "Convert these words to numbers. African AI Foundation is creating an army of AI champions"



# Tokenize the input words
tokens = tokenizer(input_words1, return_tensors="pt")

# Convert tokens to numbers (token IDs)
token_ids = tokens['input_ids']
token_ids

tensor([[  101, 10463,  2122,  2616,  2000,  3616,  1012,  3060,  9932,  3192,
          2003,  4526,  2019,  2390,  1997,  9932,  3966,   102]])

In [ ]:
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Input words - Try to make them the same no of words
input_words1 = "Convert these words to numbers. African AI Foundation is creating an army of AI champions"
input_words2 = "Converted the words to numbers. African AI Foundation has created an army of AI champions"
input_words3 =  "The African economy needs to grow for it to become very competitive like the European economy"




# Tokenize the input words
tokens1 = tokenizer(input_words1, return_tensors="pt")
tokens2 = tokenizer(input_words2, return_tensors="pt")
tokens3 = tokenizer(input_words3, return_tensors="pt")

# Convert tokens to numbers (token IDs)
token_ids = tokens['input_ids']


In [ ]:
tokens3 = tokenizer(input_words3, return_tensors="pt")
print("\n\n token 1 token ids ", tokens1['input_ids'], " \n\n token 2 token ids", tokens2['input_ids'], "\n\n input 3 token ids ", tokens2['input_ids'])



 token 1 token ids  tensor([[  101, 10463,  2122,  2616,  2000,  3616,  1012,  3060,  9932,  3192,
          2003,  4526,  2019,  2390,  1997,  9932,  3966,   102]])  

 token 2 token ids tensor([[ 101, 4991, 1996, 2616, 2000, 3616, 1012, 3060, 9932, 3192, 2038, 2580,
         2019, 2390, 1997, 9932, 3966,  102]]) 

 input 3 token ids  tensor([[ 101, 4991, 1996, 2616, 2000, 3616, 1012, 3060, 9932, 3192, 2038, 2580,
         2019, 2390, 1997, 9932, 3966,  102]])


In [ ]:
#Cosine Similarity search between token 1 and 2. Higher number means very similar

from numpy import dot
from numpy.linalg import norm

cos_sim = dot(tokens1.input_ids[0], tokens2.input_ids[0])/(norm(tokens1.input_ids[0])*norm(tokens2.input_ids[0]))
cos_sim

0.9622583131501405

In [ ]:
#Cosine Similarity search between token 2 and 3. Lower number means less similar

cos_sim = dot(tokens2.input_ids[0], tokens3.input_ids[0])/(norm(tokens2.input_ids[0])*norm(tokens3.input_ids[0]))
cos_sim

0.6601614588771935